// generated by `sqlx migrate build-script`
fn main() {
    // SQLX_OFFLINE_DIR is set via rustc_env in BUILD.bazel for Bazel builds
    // For Cargo builds, it should be set in the environment or use the default

    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
}
