// generated by `sqlx migrate build-script`
fn main() {
    // Try to find .sqlx directory and set SQLX_OFFLINE_DIR to absolute path
    // This works around Bazel's strip_prefix issue
    let sqlx_paths = [
        ".tmp_git_root/.sqlx",  // When built with Bazel (strip_prefix applied)
        "../../.sqlx",          // When built with Cargo from crates/lakekeeper
        ".sqlx",                // When built from workspace root
    ];

    for path in &sqlx_paths {
        if let Ok(abs_path) = std::fs::canonicalize(path) {
            println!("cargo:rustc-env=SQLX_OFFLINE_DIR={}", abs_path.display());
            println!("cargo:warning=Setting SQLX_OFFLINE_DIR to: {}", abs_path.display());
            break;
        }
    }

    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
}
